package edinet

// generated by "schematyper --package=edinet --root-type=EdinetDocumentResponse -o edinet/gen_edinet_response.go gen/edinet_response.json" -- DO NOT EDIT

type EdinetDocumentResponse struct {
	Metadata Metadata `json:"metadata,omitempty"`
	Results  []Result `json:"results,omitempty"`
}

type Metadata struct {
	Message         string    `json:"message,omitempty"`
	Parameter       Parameter `json:"parameter,omitempty"`
	ProcessDateTime string    `json:"processDateTime,omitempty"`
	Resultset       Resultset `json:"resultset,omitempty"`
	Status          string    `json:"status,omitempty"`
	Title           string    `json:"title,omitempty"`
}

type Parameter struct {
	Date string `json:"date,omitempty"`
	Type string `json:"type,omitempty"`
}

type Result struct {
	AttachDocFlag        string `json:"attachDocFlag,omitempty"`
	CsvFlag              string `json:"csvFlag,omitempty"`
	CurrentReportReason  string `json:"currentReportReason,omitempty"`
	DisclosureStatus     string `json:"disclosureStatus,omitempty"`
	DocDescription       string `json:"docDescription,omitempty"`
	DocID                string `json:"docID,omitempty"`
	DocInfoEditStatus    string `json:"docInfoEditStatus,omitempty"`
	DocTypeCode          string `json:"docTypeCode,omitempty"`
	EdinetCode           string `json:"edinetCode,omitempty"`
	EnglishDocFlag       string `json:"englishDocFlag,omitempty"`
	FilerName            string `json:"filerName,omitempty"`
	FormCode             string `json:"formCode,omitempty"`
	FundCode             string `json:"fundCode,omitempty"`
	IssuerEdinetCode     string `json:"issuerEdinetCode,omitempty"`
	Jcn                  string `json:"JCN,omitempty"`
	LegalStatus          string `json:"legalStatus,omitempty"`
	OpeDateTime          string `json:"opeDateTime,omitempty"`
	OrdinanceCode        string `json:"ordinanceCode,omitempty"`
	ParentDocID          string `json:"parentDocID,omitempty"`
	PdfFlag              string `json:"pdfFlag,omitempty"`
	PeriodEnd            string `json:"periodEnd,omitempty"`
	PeriodStart          string `json:"periodStart,omitempty"`
	SecCode              string `json:"secCode,omitempty"`
	SeqNumber            int    `json:"seqNumber,omitempty"`
	SubjectEdinetCode    string `json:"subjectEdinetCode,omitempty"`
	SubmitDateTime       string `json:"submitDateTime,omitempty"`
	SubsidiaryEdinetCode string `json:"subsidiaryEdinetCode,omitempty"`
	WithdrawalStatus     string `json:"withdrawalStatus,omitempty"`
	XbrlFlag             string `json:"xbrlFlag,omitempty"`
}

type Resultset struct {
	Count int `json:"count,omitempty"`
}
